### ISSUE TITLE
TLS configuration Documentation Update

### ISSUE THREAD

**Issue by maxswjeon** [dnknth/ldap-ui#12]
I'm using [osixia/docker-openldap](https://github.com/osixia/docker-openldap) with TLS_ENFORCE, which enforces TLS connections (LDAPS) on all LDAP connections.
When using TLS, the Python library verifies host certificate and hostname, which can be quite a trouble when run in same docker-compose environments.
I bypassed this error with [network aliases](https://docs.docker.com/compose/compose-file/compose-file-v3/#aliases). 

Please add this to the documentation or give options whether to verify hostname.

My example
```
version: '3.7'
services:
  openldap:
    image: osixia/openldap
    container_name: ldap_server
    restart: always
    ports:
      - 10389:389
      - 10636:636
    volumes:
      - ./data/current:/var/lib/ldap
      - ./config/server/slapd:/etc/ldap/slapd.d
      # - ./config/server/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - certificates:/container/service/slapd/assets/certs
    environment:
      - LDAP_ORGANISATION=Codingbear Org.
      - LDAP_DOMAIN=codingbear.kr
      - LDAP_ADMIN_PASSWORD=$ADMIN_PASSWORD
      - LDAP_CONFIG_PASSWORD=$CONFIG_PASSWORD
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_PASSWORD=$READONLY_PASSWORD
      - LDAP_TLS_CRT_FILENAME=ldap.codingbear.kr_ecc/fullchain.cer
      - LDAP_TLS_KEY_FILENAME=ldap.codingbear.kr_ecc/ldap.codingbear.kr.key
      - LDAP_TLS_CA_CRT_FILENAME=ldap.codingbear.kr_ecc/ca.cer
      - LDAP_TLS_ENFORCE=true
      - LDAP_TLS_VERIFY_CLIENT=never
      - KEEP_EXISTING_CONFIG=false
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
    networks:
      default:
        aliases:
          - $LDAP_HOSTNAME

  admin:
    image: dnknth/ldap-ui
    container_name: ldap_admin
    restart: always
    ports:
      - 127.0.0.1:1900:5000
    environment:
      - LDAP_URL=ldaps://$LDAP_HOSTNAME
      - BASE_DN=dc=codingbear,dc=kr
    depends_on:
      - openldap
    networks:
      - default

volumes:
  certificates:
    external: true

networks:
  default:
```
