### ISSUE TITLE
Cannot work in Chrome(Version 122.0.6261.112 (Official Build) (x86_64))

### ISSUE THREAD

**Issue by ninggf** [dnknth/ldap-ui#53]
The issue is:

TypeError: Cannot read properties of undefined (reading 'syntaxes')
    at new qa (index-37fb71fe.js:17:50422)
    at index-37fb71fe.js:17:57634

**Comment by dnknth** [comment]
Please provide complete logs, the error above is likely caused by something that happened previously.

**Comment by dnknth** [comment]
Closing this due to lack of information.

**Comment by ninggf** [comment]
<img width="540" alt="image" src="https://github.com/dnknth/ldap-ui/assets/19420005/b7b5eed6-6549-405e-ad77-74b57f91d73d">

The issue always exist.

My docker-compose.yml like:

```yaml
version: "3.8"

services:
  ldapui:
    image: dnknth/ldap-ui:latest
    container_name: ldapui
    restart: always
    depends_on:
      openldap:
        condition: service_healthy
    ports:
      - 8500:5000
    networks:
      - esnetwork
    environment:
      LDAP_URL: ldap://openldap:389/
      BASE_DN: "dc=abc,dc=com"
      LOGIN_ATTR: cn
      BIND_PATTERN: "%s,dc=abc,dc=com"
```
