### ISSUE TITLE
The page crashed when login with error username/password

### ISSUE THREAD

**Issue by ninggf** [dnknth/ldap-ui#58]
<img width="1081" alt="image" src="https://github.com/dnknth/ldap-ui/assets/19420005/d7aea877-5926-49c8-9e67-9290feb808e0">

docker-compose.yml like:

```yaml
version: "3.8"

services:
  ldapui:
    image: dnknth/ldap-ui:latest
    container_name: ldapui
    restart: always
    depends_on:
      openldap:
        condition: service_healthy
    ports:
      - 8500:5000
    networks:
      - esnetwork
    environment:
      LDAP_URL: ldap://openldap:389/
      BASE_DN: dc=abc,dc=com
      LOGIN_ATTR: cn
      BIND_PATTERN: "%s,dc=abc,dc=com"
```

By the way, it's a very good thing if there is a  logout button!
