### ISSUE TITLE
DN with slashes cause 404 error

### ISSUE THREAD

**Issue by RicardoJeronimo** [dnknth/ldap-ui#66]
In my LDAP server I have the following entries to allow roaming user directories:

```yaml
dn: cn=/ldap,nisMapName=auto.master,dc=domain,dc=lan
objectClass: nisObject
cn: /ldap
nisMapEntry: ldaps:domain.lan:nisMapName=auto.home,dc=domain,dc=lan
nisMapName: auto.master

dn: cn=/,nisMapName=auto.home,dc=domain,dc=lan
objectClass: nisObject
cn: /
nisMapEntry: share.domain.lan:/ldap/&
nisMapName: auto.home

dn: cn=/-,nisMapName=auto.master,dc=domain,dc=lan
objectClass: nisObject
cn: /-
nisMapEntry: ldaps:domain.lan:nisMapName=auto.share,dc=domain,dc=lan
nisMapName: auto.master

dn: cn=/share,nisMapName=auto.share,dc=domain,dc=lan
objectClass: nisObject
cn: /share
nisMapEntry: share.domain.lan:/share
nisMapName: auto.share
```

Since these DNs contain a slash, ldap-ui returns a 404 error:

![Image](https://github.com/user-attachments/assets/0f381500-6228-4546-9c11-275367973077)

![Image](https://github.com/user-attachments/assets/86803909-0760-4ed7-acbb-b7897ce4b466)
